name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'
    - name: Run tests
      run: |
        find . -type d -maxdepth 1 -not -name '.*' -exec sh -c 'cd {}; go test ./...' \;
